AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - docs/**/*
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockNesting:
  Max: 5
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Style/AccessorMethodName:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: true
Style/MultilineOperationIndentation:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Style/FormatString:
  Enabled: true
Lint/Eval:
  Enabled: true

