AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/bundle/**/*
    - docs/**/*
    - test/rails4_dummy/**/*
    - test/rails5_dummy/**/*
    - test/fixtures/**/*
    # Get the code passing first then we will enable for tests
    - test/**/*    
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Max: 160
Metrics/BlockNesting:
  Max: 5
Metrics/BlockLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Naming/AccessorMethodName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/PredicateName:
  Enabled: true
Style/TernaryParentheses:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/IfInsideElse:
  Enabled: false    
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/MultilineOperationIndentation:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Style/FormatString:
  Enabled: true
Security/Eval:
  Enabled: true
