language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem uninstall bundler
  - gem install bundler -v '< 2'