language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6.1"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
script:
  - bundle exec rake rubocop
  - bundle exec rake
  - bundle exec rake forked_tests
before_install:
  - echo 'this is a hack to clear default bundler and force bundler 1.17.3'
  - ls /home/travis/.rvm/gems/
  - rm /home/travis/.rvm/gems/ruby-2.3.7@global/specifications/bundler-2.0.1.gemspec || true
  - rm /home/travis/.rvm/gems/ruby-2.4.6@global/specifications/bundler-2.0.1.gemspec || true
  - rm /home/travis/.rvm/gems/ruby-2.5.5@global/specifications/bundler-2.0.1.gemspec || true
  - gem uninstall bundler || true
  - gem install bundler -v '1.17.3'
  - bundler --version
