language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
before_install:
    - for dir in $(echo $GEM_PATH | tr ':' ' '); do gem uninstall -i $dir bundler -a -x; done
    - gem install bundler -v '< 2'
