language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6.1"
  #  - "2.7" #disable until I can detect and exclude rails4 for on Ruby 2.7
  - jruby-9.2.6.0

env:
  global:
    # --dev improves JRuby startup time
    # See https://github.com/jruby/jruby/wiki/Improving-startup-time
    - JRUBY_OPTS="--dev"

cache:
  bundler: true
  directories:
    - $HOME/lua51
gemfile:
  - Gemfile
  - Gemfile.rails6
services:
  - redis-server
script:
  - sudo ./lua/install.sh
  - $HOME/lua51/bin/busted lua/test/*
  - bundle exec rake rubocop
  - COVERBAND_HASH_REDIS_STORE=t bundle exec rake
  - COVERBAND_HASH_REDIS_STORE=t bundle exec rake forked_tests
  - bundle exec rake
  - bundle exec rake forked_tests
  # remove this for now as it is flaky
  # passes locally on 2.3.5 on travis passes sometimes on 2.4 and always on 2.6.1
  #- bundle exec rake benchmarks:memory
  - bundle exec rake benchmarks
