language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6.1"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v '1.17.3'
