language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - redis-server
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rm /home/travis/.rvm/rubies/2.3.7/lib/ruby/gems/2.3.0/specifications/default/bundler.gemspec || true
  - gem uninstall bundler || true
  - which bundler || true
  - ls /home/travis/.rvm/gems/ruby-2.3.7@global || true
  - gem install bundler -v '1.17.3'
  - bundler --version